spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          spring:
            client-id: "bff-client"
            client-secret: "secret"
            authorization-grant-type: "authorization_code"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "user.write"
        provider:
          spring:
            issuer-uri: http://localhost:9000

  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/**, /db/**, /ws/**
          filters:
            - TokenRelay=
        - id: vue
          uri: http://127.0.0.1:4200
          predicates:
            - Path=/**, /spa/**, /ui/**, /frontend/**
          filters:
            - RewritePath=/.*,/ # Rewrite all matched paths to "/"

server:
  shutdown: graceful

management:
  endpoint:
    health:
      access: read_only

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    web: debug
