spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: "spring"
            client-id: "oidc-client"
            client-secret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "openid"
        provider:
          spring:
            issuer-uri: http://localhost:9000

  cloud:
    gateway:
      routes:
        - id: authorization
          uri: http://localhost:9000
          predicates:
            - Path=/logout
        - id: resource
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/api/**, /db/**, /ws/**
          filters:
            - TokenRelay=
        - id: vue
          uri: http://127.0.0.1:4200
          predicates:
            - Path=/**

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
      access: read_only
