spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: "spring"
            client-id: "gateway"
            client-secret: "secret"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_basic"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - "user.read"
              - "user.write"
              - "openid"
        provider:
          spring:
            issuer-uri: http://localhost:9000

  cloud:
    gateway:
#      default-filters:
#        - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ui-vue-search
          uri: http://127.0.0.1:4200
          predicates:
            - Path=/, /spa/**, /ui/**, /frontend/**
          filters:
            - RewritePath=/.*,/ # Rewrite all matched paths to "/"
            - SaveSession
            - TokenRelay

        - id: ui-vue-admin
          uri: http://127.0.0.1:4201
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/.*,/ # Rewrite all matched paths to "/"
            - SaveSession
            - TokenRelay

        - id: ui-vue-user
          uri: http://127.0.0.1:4202
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/.*,/ # Rewrite all matched paths to "/"
            - SaveSession
            - TokenRelay

        - id: api
          uri: http://localhost:8081
          predicates:
              - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - SaveSession
            - TokenRelay
            - RemoveRequestHeader=Cookie

        - id: json-placeholder-client-search
          uri: http://localhost:8082
          predicates:
            - Path=/json-placeholder/users/search
          filters:
            - RewritePath=/json-placeholder/(?<segment>.*), /$\{segment}
            - SaveSession
            - TokenRelay
            - RemoveRequestHeader=Cookie

        - id: json-placeholder-client
          uri: http://localhost:8082
          predicates:
          - Path=/json-placeholder/**, /json-placeholder/users/**
          filters:
            - RewritePath=/json-placeholder/(?<segment>.*), /$\{segment}
            - SaveSession
            - TokenRelay
            - RemoveRequestHeader=Cookie

        - id: json-placeholder
          uri: https://jsonplaceholder.typicode.com
          predicates:
              - Path=/json-placeholder-raw/**
          filters:
            - RewritePath=/json-placeholder-raw/(?<segment>.*), /$\{segment}
            - SaveSession
            - RemoveRequestHeader=Cookie

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"