spring:
  application:
    name: oauth2-auth-server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          bff-client:
            registration:
              client-id: "bff-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/spring"
              scopes:
                - "user.read"
                - "user.write"

server:
  port: 9000
  shutdown: graceful

management:
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: trace
    root: INFO
    org.springframework.web: INFO
    org.springframework.security.oauth2: DEBUG