spring:
  application:
    name: oauth2-auth-server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          gateway:
            registration:
              client-id: "gateway"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/gateway"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
            require-authorization-consent: true

server:
  port: 9000

management:
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: trace
    root: INFO
    org.springframework.web: INFO
    org.springframework.security.oauth2: DEBUG