spring:
  application:
    name: db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  flyway:
    enabled: false

  webflux:
    problemdetails:
      enabled: true

server:
  port: 8083
