name: bff pattern pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  docker-image-build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      max-parallel: 1
      continue-on-error: false
      matrix:
        folder: [api-gateway, oauth2-auth-server, websocket, db, api]
    defaults:
      run:
        shell: bash
        working-directory: ./${{matrix.folder}}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Display the folder structure
        run: |
          echo ${{ matrix.folder}}
          ls -al
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: build buildpack image
        run: |
          ./mvnw -B spring-boot:build-image \
                -DskipTests \
                -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}-${{ matrix.folder}}:${{github.run_id}}
          
          docker tag ghcr.io/${{ github.repository }}-${{ matrix.folder}}:${{github.run_id}} ghcr.io/${{ github.repository }}-${{ matrix.folder}}:main
          
          docker tag ghcr.io/${{ github.repository }}-${{ matrix.folder}}:${{github.run_id}} ghcr.io/${{ github.repository }}-${{ matrix.folder}}:$(date +%d%m%Y%H%M)
          
          docker images

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push buildpack image
        run: docker push -a ghcr.io/${{ github.repository }}
